server:
  port: 8990

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  sa-token:
    token-name: token
    timeout: 2592000
    activity-timeout: 1800
    allow-concurrent-login: false
    is-share: false
    token-style: uuid
    is-log: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    cache: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml