server:
  port: 8990

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: blog
    password: 123456
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  freemarker:
    template-loader-path: file:///${user.home}/.blog/theme/templates/
    suffix: .ftl
    cache: true
    check-template-location: false
  resources:
    static-locations: file:///${user.home}/.blog/theme/static/

sa-token:
  token-name: token
  timeout: 2592000
  activity-timeout: 1800
  is-share: false
  token-style: uuid
  is-log: false
  is-concurrent: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:logback-pro.xml
